In [2]:
import pandas as pd

df = pd.read_csv("email.csv")

# clean
df["Category"] = df["Category"].str.lower().str.strip()
df["Message"] = df["Message"].fillna("")

# keep valid rows
df = df[df["Category"].isin(["ham", "spam"])]

# Y (labels)
df["y"] = df["Category"].map({"ham": 0, "spam": 1})

X_text = df["Message"]
y = df["y"]

In [3]:
df

     Category                                            Message  y
0         ham  Go until jurong point, crazy.. Available only ...  0
1         ham                      Ok lar... Joking wif u oni...  0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...  1
3         ham  U dun say so early hor... U c already then say...  0
4         ham  Nah I don't think he goes to usf, he lives aro...  0
...       ...                                                ... ..
5567     spam  This is the 2nd time we have tried 2 contact u...  1
5568      ham               Will ü b going to esplanade fr home?  0
5569      ham  Pity, * was in mood for that. So...any other s...  0
5570      ham  The guy did some bitching but I acted like i'd...  0
5571      ham                         Rofl. Its true to its name  0

[5572 rows x 3 columns]

In [5]:
# Train / Test split
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [6]:
# Convert text → numbers (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english", max_features=10000)

X_train = vectorizer.fit_transform(X_train_text)
X_test  = vectorizer.transform(X_test_text)

In [8]:
# Train model (Gradient Descent)
from sklearn.linear_model import SGDClassifier

model = SGDClassifier(loss="log_loss", random_state=42)
# Input → Output → Loss → Gradient Descent → Update weights
model.fit(X_train, y_train)

SGDClassifier(loss='log_loss', random_state=42)

In [9]:
# Predict on X_test
y_pred = model.predict(X_test)          # final class (0/1)
y_prob = model.predict_proba(X_test)    # probabilities

In [11]:
y_prob

array([[0.98015791, 0.01984209],
       [0.98938555, 0.01061445],
       [0.98337581, 0.01662419],
       ...,
       [0.93442904, 0.06557096],
       [0.94691748, 0.05308252],
       [0.97215752, 0.02784248]], shape=(1115, 2))

In [12]:
# Calculate loss on X_test
from sklearn.metrics import log_loss, accuracy_score

test_loss = log_loss(y_test, y_prob)
test_accuracy = accuracy_score(y_test, y_pred)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

Test Loss: 0.10084271683114471
Test Accuracy: 0.9775784753363229

In [13]:
# See some real predictions

results = pd.DataFrame({
    "Message": X_test_text.values[:10],
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10],
    "Spam_Probability": y_prob[:10, 1]
})

results

,Message,Actual,Predicted,Spam_Probability
0,No need to buy lunch for me.. I eat maggi mee..,0,0,0.019842
1,Ok im not sure what time i finish tomorrow but...,0,0,0.010614
2,Waiting in e car 4 my mum lor. U leh? Reach ho...,0,0,0.016624
3,"You have won ?1,000 cash or a ?2,000 prize! To...",1,1,0.892236
4,If you r @ home then come down within 5 min,0,0,0.044249
5,No need lar. Jus testing e phone card. Dunno n...,0,0,0.032869
6,Wot about on wed nite I am 3 then but only til 9!,0,0,0.044403
7,Hey you gave them your photo when you register...,0,0,0.041693
8,"Hello, my boytoy! I made it home and my consta...",0,0,0.007116
9,Eh u remember how 2 spell his name... Yes i di...,0,0,0.025536